# Generated by Django 6.0.1 on 2026-01-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('coupon', 'Coupon'), ('replacement', 'Replacement'), ('exclusive', 'Exclusive'), ('premium', 'Premium'), ('buy1get1', 'Buy 1 Get 1'), ('misc', 'Misc')], default='misc', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_type',
            field=models.CharField(blank=True, choices=[('full-rim', 'Full Rim'), ('half-rim', 'Half Rim'), ('rimless', 'Rimless')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_prescription_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, choices=[('round', 'Round'), ('rectangle', 'Rectangle'), ('square', 'Square'), ('oval', 'Oval'), ('aviator', 'Aviator'), ('cat-eye', 'Cat Eye'), ('geometric', 'Geometric')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariant')),
            ],
        ),
    ]
