# Generated by Django 6.0.1 on 2026-01-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_brand_rename_price_product_base_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extra-narrow", "Extra Narrow"),
                    ("narrow", "Narrow"),
                    ("medium", "Medium"),
                    ("wide", "Wide"),
                    ("extra-wide", "Extra Wide"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light"),
                    ("average", "Average"),
                    ("heavy", "Heavy"),
                ],
                max_length=20,
            ),
        ),
    ]
