# Generated by Django 6.0.1 on 2026-01-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_productvariant_size_weight_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extra-narrow", "Extra Narrow"),
                    ("narrow", "Narrow"),
                    ("medium", "Medium"),
                    ("wide", "Wide"),
                    ("extra-wide", "Extra Wide"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light"),
                    ("average", "Average"),
                    ("heavy", "Heavy"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/")),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
