# Generated by Django 6.0.1 on 2026-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_variant_add_product_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tryon_glasses",
            field=models.ImageField(blank=True, null=True, upload_to="tryon/"),
        ),
    ]
