# Generated by Django 6.0.1 on 2026-01-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_tryon_glasses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tryon_glasses",
        ),
    ]
